[package]
name = "cpp-demo-analyzer"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# 核心接口
analyzer-core = { path = "../../crates/analyzer-core" }
abi_stable = { workspace = true }
anyhow = { workspace = true }

# C++ 互操作
cxx = "1.0"

[build-dependencies]
cxx-build = "1.0"
